---

- name: Loading Wireless management tasks
  include: wireless.yml
  when: manage_wireless_interfaces|default(False)

- name: handling ether interfaces
  include: iface_ethers.yml
  when:
    - managed_ethers is defined
    - managed_ethers is iterable

- name: handling bond interfaces
  include: iface_bonds.yml
  when:
    - managed_bonds is defined
    - managed_bonds is iterable

- name: handling vlan interfaces
  include: iface_vlans.yml
  when:
    - managed_vlans is defined
    - managed_vlans is iterable

- name: handling interface lists
  tags:
    - never
  include: iface_lists.yml
  when:
    - managed_interface_lists is defined
    - managed_interface_lists is iterable

...
