---
- name: create backup script
  routeros_command:
    commands:
      - "/system scheduler add interval=1w name=backup on-event=\"system backup save name=today.backup\" policy=ftp,reboot,read,write,policy,test,password,sniff,sensitive,romon start-date=jun/11/2018 start-time=00:00:00"
      - /user group add name=ftp policy="ftp,read,sensitive,!local,!telnet,!ssh,!reboot,!write,!policy,!test,!winbox,!password,!web,!sniff,!api,!romon,!dude,!tikapp"
      - "/user add address={{ backup_src_ip }} group=ftp name=ftp"
      - "/user set ftp password={{ backup_password }}"
  when:
    - backup_script | bool
    - backup_password is defined
    - backup_src_ip is defined

- name: auto upgrade script
  routeros_command:
    commands:
      - "/system scheduler add interval=1w name=upgrade on-event=\"system package update check-for-updates once :delay 1s; :if ( [get status] = \\\"New version is available\\\") do={ install }\" policy=ftp,reboot,read,write,policy,test,password,sniff,sensitive,romon start-date=jun/12/2018 start-time=00:00:00"
  when: upgrade_script | bool

- name: set ntp client (dns based)
  routeros_command:
    commands:
      - "/system ntp client set enabled=yes server-dns-names={{ ntp_client_dnsnames }}"
  when:
    - set_ntp_client_dns is defined
    - set_ntp_client_dns | bool

- name: set ntp client (ip based)
  routeros_command:
    commands:
      - "/system ntp client set enabled=yes primary-ntp={{ ntp_client_ip1 }} secondary-ntp={{ ntp_client_ip2 }}"
  when:
    - set_ntp_client_ip is defined
    - set_ntp_client_ip| bool

- name: set logging remote
  routeros_command:
    commands:
      - "/system logging action set number=[ find name=remote ] target=\"remote\" remote={{ system_logging_remote_ip }} remote-port={{ system_logging_remote_ip_port }} src-address=0.0.0.0 bsd-syslog=yes syslog-time-format=bsd-syslog syslog-facility=daemon syslog-severity=alert"
  when:
    - set_system_logging_remote is defined
    - set_system_logging_remote| bool

- name: set logging
  routeros_command:
    commands:
      - "/system logging add action={{ item.0.action }} topics={{ item.1.name }}"
  with_subelements:
    - "{{ system_logging }}"
    - topics
  when:
    - set_system_logging is defined
    - set_system_logging| bool
